### ISSUE TITLE
ドメインまでのリンクを作成する場合の問題点

### ISSUE THREAD

**Issue by yunapanpan12** [furuhashilab/sotsuron2021#85]

**Comment by yunapanpan12** [comment]
# ドメインのまとめ方について
## 逗子市、三浦市のドメインについて
中間発表で、横浜市の区ごとにハザードマップをまとめた際、ドメインまで同じリンクの表示であれば、分けてまとめる必要はないとおっしゃっていたので、横浜市は一つにまとめました。

ですが、横浜市は地図情報だけまとめられたウェブサイトがあるので、ドメインまでの情報で良いのですが、

逗子市や三浦市の中の各地区のハザードマップをドメインだけでまとめると、地理系ウェブサイトではなく、自治体自体の公式ウェブサイトにとんでしまいます。

この場合地理系ウェブサイトに限定したホワイトリスト作りにならなくなってしまうので、ドメインまでのリンクだけにするべきか否か教えて頂きたいです。

# 防災情報以外も調べるべきか
行政の公式で発信している地図が防災関連に限られる場合、観光、農地、文化財などに関する地図で行政以外の他の団体が作成しているウェブサイトを調べるべきでしょうか

**Comment by yunapanpan12** [comment]
## 横浜地域
### 横浜市共通
* 横浜市行政地図情報提供システム,https://wwwm.city.yokohama.lg.jp


****
## 川崎地域
### 川崎市
* ガイドマップかわさきhttps://kawasaki.geocloud.jp
****
## 横須賀三浦地域
### 横須賀市
* よこすか　わが町ガイド,https://www2.wagmap.jp/
### 鎌倉市
* 鎌倉市防災情報マップ 地図情報公開サービス,https://www2.wagmap.jp/kamakura-hazard

### 逗子市
* 逗子市津波ハザードマップ１,https://www.city.zushi.kanagawa.jp/global-image/units/115865/1-20190606075726.pdf
* 逗子市津波ハザードマップ２,https://www.city.zushi.kanagawa.jp/global-image/units/115866/1-20191225144544.pdf
* 逗子市公式ホームページ,https://www.city.zushi.kanagawa.jp/
### 三浦市
* 三浦市津波ハザードマップ　三崎地区表紙面,http://www.city.miura.kanagawa.jp/kikikanri/documents/tsunami-hazard-map_misaki_front_h30.pdf
* 三浦市津波ハザードマップ　三崎地区裏面,http://www.city.miura.kanagawa.jp/kikikanri/documents/tsunami-hazard-map_misaki_back_h30.pdf
* 三浦市津波ハザードマップ　南下浦地区表紙面,http://www.city.miura.kanagawa.jp/kikikanri/documents/tsunami-hazard-map_minamishitaura_front_h30.pdf
* 三浦市津波ハザードマップ　南下浦地区裏面,http://www.city.miura.kanagawa.jp/kikikanri/documents/tsunami-hazard-map_minamishitaura_back_h30.pdf
* 三浦市公式ホームページ,http://www.city.miura.kanagawa.jp

**Comment by mapconcierge** [comment]
「ホワイトリストを作る」という目的であれば地理系ウェブサイトだけではなく、自治体自体の公式ウェブサイトも含めるかたちで全く問題ないです。

おそらく、「ホワイトリストとは何か？」「インターネットにおけるドメインとは何か？」という本質的な理解ができていないと思われるので、言葉の意味をしっかり調べると良いです。

例：
* https://www.city.zushi.kanagawa.jp/global-image/units/115866/1-20191225144544.pdf はドメインではない。
* https://www.city.zushi.kanagawa.jp はドメインである。
* ドメインとURLは同じではない。
* https://www.city.zushi.kanagawa.jp/global-image/units/115865/1-20190606075726.pdf と
https://www.city.zushi.kanagawa.jp/global-image/units/115866/1-20191225144544.pdf はホワイトリスト用ドメインとしては https://www.city.zushi.kanagawa.jp だけでまとめてよい。個別のハザードマップのURLは不要。ドメイン一つに対して、サンプルURLが一つあればよい。
